
######slot2 : awg
set_property PACKAGE_PIN AP15 [get_ports {TRIGGER0_P[0]}]
set_property PACKAGE_PIN AR13 [get_ports {DCO0_P[0]}]
set_property PACKAGE_PIN AW18 [get_ports {ID_DOWN[0]}]
set_property PACKAGE_PIN AW30 [get_ports {ID_UP[0]}]
set_property PACKAGE_PIN AV19 [get_ports {ID_DOWN_VALID[0]}]
set_property PACKAGE_PIN AW31 [get_ports {ID_UP_VALID[0]}]
set_property PACKAGE_PIN AU20 [get_ports {CMD_0[0]}]
set_property PACKAGE_PIN AW20 [get_ports {CMD_1[0]}]
set_property PACKAGE_PIN AW19 [get_ports {CMD_VALID[0]}]
######slot3 : awg
set_property PACKAGE_PIN AT15 [get_ports {TRIGGER0_P[1]}]
set_property PACKAGE_PIN AL12 [get_ports {DCO0_P[1]}]
set_property PACKAGE_PIN AT17 [get_ports {ID_DOWN[1]}]
set_property PACKAGE_PIN AV29 [get_ports {ID_UP[1]}]
set_property PACKAGE_PIN AT18 [get_ports {ID_DOWN_VALID[1]}]
set_property PACKAGE_PIN AV31 [get_ports {ID_UP_VALID[1]}]
set_property PACKAGE_PIN AU16 [get_ports {CMD_0[1]}]
set_property PACKAGE_PIN AU17 [get_ports {CMD_1[1]}]
set_property PACKAGE_PIN AR20 [get_ports {CMD_VALID[1]}]

######slot4 : awg
set_property PACKAGE_PIN AV16 [get_ports {TRIGGER0_P[2]}]
set_property PACKAGE_PIN AM31 [get_ports {DCO0_P[2]}]
set_property PACKAGE_PIN AN18 [get_ports {ID_DOWN[2]}]
set_property PACKAGE_PIN AU31 [get_ports {ID_UP[2]}]
set_property PACKAGE_PIN AM16 [get_ports {ID_DOWN_VALID[2]}]
set_property PACKAGE_PIN AU30 [get_ports {ID_UP_VALID[2]}]
set_property PACKAGE_PIN AP19 [get_ports {CMD_0[2]}]
set_property PACKAGE_PIN AN16 [get_ports {CMD_1[2]}]
set_property PACKAGE_PIN AN17 [get_ports {CMD_VALID[2]}]
######slot5 : awg
set_property PACKAGE_PIN AT14 [get_ports {TRIGGER0_P[3]}]
set_property PACKAGE_PIN AG12 [get_ports {DCO0_P[3]}]
set_property PACKAGE_PIN AK18 [get_ports {ID_DOWN[3]}]
set_property PACKAGE_PIN AR30 [get_ports {ID_UP[3]}]
set_property PACKAGE_PIN AG16 [get_ports {ID_DOWN_VALID[3]}]
set_property PACKAGE_PIN AU32 [get_ports {ID_UP_VALID[3]}]
set_property PACKAGE_PIN AH16 [get_ports {CMD_0[3]}]
set_property PACKAGE_PIN AK17 [get_ports {CMD_1[3]}]
set_property PACKAGE_PIN AL18 [get_ports {CMD_VALID[3]}]
######slot6 : dac
set_property PACKAGE_PIN AV14 [get_ports {TRIGGER0_P[4]}]
set_property PACKAGE_PIN AL30 [get_ports {DCO0_P[4]}]

set_property PACKAGE_PIN AD18 [get_ports {ID_DOWN[4]}]
set_property PACKAGE_PIN AP30 [get_ports {ID_UP[4]}]
set_property PACKAGE_PIN AE18 [get_ports {ID_DOWN_VALID[4]}]
set_property PACKAGE_PIN AN29 [get_ports {ID_UP_VALID[4]}]
set_property PACKAGE_PIN AJ18 [get_ports {CMD_0[4]}]
set_property PACKAGE_PIN AE17 [get_ports {CMD_1[4]}]
set_property PACKAGE_PIN AH18 [get_ports {CMD_VALID[4]}]
##########
set_property PACKAGE_PIN AT35 [get_ports {TRIGGER1_P[0]}]
set_property PACKAGE_PIN AK32 [get_ports {DCO1_P[0]}]

set_property PACKAGE_PIN AG19 [get_ports {ID_DOWN[5]}]
set_property PACKAGE_PIN AP31 [get_ports {ID_UP[5]}]
set_property PACKAGE_PIN AF19 [get_ports {ID_DOWN_VALID[5]}]
set_property PACKAGE_PIN AR31 [get_ports {ID_UP_VALID[5]}]
set_property PACKAGE_PIN AM19 [get_ports {CMD_0[5]}]
set_property PACKAGE_PIN AF18 [get_ports {CMD_1[5]}]
set_property PACKAGE_PIN AL19 [get_ports {CMD_VALID[5]}]
######slot7 : adda
set_property PACKAGE_PIN AF15 [get_ports {TRIGGER0_P[5]}]
set_property PACKAGE_PIN AN36 [get_ports {DCO0_P[5]}]

set_property PACKAGE_PIN AP35 [get_ports {ID_DOWN[6]}]
set_property PACKAGE_PIN AJ19 [get_ports {ID_UP[6]}]
set_property PACKAGE_PIN AK30 [get_ports {ID_DOWN_VALID[6]}]
set_property PACKAGE_PIN AH19 [get_ports {ID_UP_VALID[6]}]

set_property PACKAGE_PIN AL33 [get_ports {CMD_DOWN_0[0]}]
set_property PACKAGE_PIN AK31 [get_ports {CMD_DOWN_1[0]}]
set_property PACKAGE_PIN AP33 [get_ports {CMD_UP_0[0]}]
set_property PACKAGE_PIN AR32 [get_ports {CMD_UP_1[0]}]
set_property PACKAGE_PIN AK33 [get_ports {CMD_DOWN_VALID[0]}]
set_property PACKAGE_PIN AN33 [get_ports {CMD_UP_VALID[0]}]
##########
set_property PACKAGE_PIN AW33 [get_ports {TRIGGER1_P[1]}]
set_property PACKAGE_PIN L25 [get_ports {DCO1_P[1]}]

set_property PACKAGE_PIN AJ33 [get_ports {ID_DOWN[7]}]
set_property PACKAGE_PIN AH31 [get_ports {ID_UP[7]}]
set_property PACKAGE_PIN AF30 [get_ports {ID_DOWN_VALID[7]}]
set_property PACKAGE_PIN AG30 [get_ports {ID_UP_VALID[7]}]

set_property PACKAGE_PIN AH29 [get_ports {CMD_DOWN_0[1]}]
set_property PACKAGE_PIN AH28 [get_ports {CMD_DOWN_1[1]}]
set_property PACKAGE_PIN AJ28 [get_ports {CMD_UP_0[1]}]
set_property PACKAGE_PIN AJ30 [get_ports {CMD_UP_1[1]}]
set_property PACKAGE_PIN AE30 [get_ports {CMD_DOWN_VALID[1]}]
set_property PACKAGE_PIN AJ29 [get_ports {CMD_UP_VALID[1]}]
######slot9 : dac  : 6
set_property PACKAGE_PIN AR12 [get_ports {TRIGGER0_P[6]}]
set_property PACKAGE_PIN K26 [get_ports {DCO0_P[6]}]

set_property PACKAGE_PIN AK37 [get_ports {ID_DOWN[8]}]
set_property PACKAGE_PIN AM36 [get_ports {ID_UP[8]}]
set_property PACKAGE_PIN AL37 [get_ports {ID_DOWN_VALID[8]}]
set_property PACKAGE_PIN AH32 [get_ports {ID_UP_VALID[8]}]
set_property PACKAGE_PIN AM37 [get_ports {CMD_0[6]}]
set_property PACKAGE_PIN AK35 [get_ports {CMD_1[6]}]
set_property PACKAGE_PIN AK36 [get_ports {CMD_VALID[6]}]


set_property PACKAGE_PIN AV33 [get_ports {TRIGGER1_P[2]}]
set_property PACKAGE_PIN J26 [get_ports {DCO1_P[2]}]

set_property PACKAGE_PIN R30 [get_ports {ID_DOWN[9]}]
set_property PACKAGE_PIN AG29 [get_ports {ID_UP[9]}]
set_property PACKAGE_PIN M32 [get_ports {ID_DOWN_VALID[9]}]
set_property PACKAGE_PIN AJ31 [get_ports {ID_UP_VALID[9]}]
set_property PACKAGE_PIN AJ39 [get_ports {CMD_0[7]}]
set_property PACKAGE_PIN AK38 [get_ports {CMD_1[7]}]
set_property PACKAGE_PIN L33 [get_ports {CMD_VALID[7]}]
######slot10 : dac
set_property PACKAGE_PIN AP14 [get_ports {TRIGGER0_P[7]}]
set_property PACKAGE_PIN H27 [get_ports {DCO0_P[7]}]

set_property PACKAGE_PIN N29 [get_ports {ID_DOWN[10]}]
set_property PACKAGE_PIN AE28 [get_ports {ID_UP[10]}]
set_property PACKAGE_PIN M31 [get_ports {ID_DOWN_VALID[10]}]
set_property PACKAGE_PIN AF28 [get_ports {ID_UP_VALID[10]}]
set_property PACKAGE_PIN P29 [get_ports {CMD_0[8]}]
set_property PACKAGE_PIN P30 [get_ports {CMD_1[8]}]
set_property PACKAGE_PIN P28 [get_ports {CMD_VALID[8]}]

set_property PACKAGE_PIN AT34 [get_ports {TRIGGER1_P[3]}]
set_property PACKAGE_PIN G25 [get_ports {DCO1_P[3]}]

set_property PACKAGE_PIN L32 [get_ports {ID_DOWN[11]}]
set_property PACKAGE_PIN T28 [get_ports {ID_UP[11]}]
set_property PACKAGE_PIN M29 [get_ports {ID_DOWN_VALID[11]}]
set_property PACKAGE_PIN AF29 [get_ports {ID_UP_VALID[11]}]
set_property PACKAGE_PIN N27 [get_ports {CMD_0[9]}]
set_property PACKAGE_PIN N28 [get_ports {CMD_1[9]}]
set_property PACKAGE_PIN M30 [get_ports {CMD_VALID[9]}]
######slot11 : awg
set_property PACKAGE_PIN AH14 [get_ports {TRIGGER0_P[8]}]
set_property PACKAGE_PIN H31 [get_ports {DCO0_P[8]}]

set_property PACKAGE_PIN J33 [get_ports {ID_DOWN[12]}]
set_property PACKAGE_PIN R27 [get_ports {ID_UP[12]}]
set_property PACKAGE_PIN K33 [get_ports {ID_DOWN_VALID[12]}]
set_property PACKAGE_PIN R28 [get_ports {ID_UP_VALID[12]}]
set_property PACKAGE_PIN L29 [get_ports {CMD_0[10]}]
set_property PACKAGE_PIN L30 [get_ports {CMD_1[10]}]
set_property PACKAGE_PIN K30 [get_ports {CMD_VALID[10]}]
######slot12 : awg
set_property PACKAGE_PIN AH13 [get_ports {TRIGGER0_P[9]}]
set_property PACKAGE_PIN E31 [get_ports {DCO0_P[9]}]

set_property PACKAGE_PIN F28 [get_ports {ID_DOWN[13]}]
set_property PACKAGE_PIN P25 [get_ports {ID_UP[13]}]
set_property PACKAGE_PIN E26 [get_ports {ID_DOWN_VALID[13]}]
set_property PACKAGE_PIN P24 [get_ports {ID_UP_VALID[13]}]
set_property PACKAGE_PIN F27 [get_ports {CMD_0[11]}]
set_property PACKAGE_PIN G27 [get_ports {CMD_1[11]}]
set_property PACKAGE_PIN E25 [get_ports {CMD_VALID[11]}]

######slot13 : awg
set_property PACKAGE_PIN AK13 [get_ports {TRIGGER0_P[10]}]
set_property PACKAGE_PIN B30 [get_ports {DCO0_P[10]}]

set_property PACKAGE_PIN B27 [get_ports {ID_DOWN[14]}]
set_property PACKAGE_PIN N26 [get_ports {ID_UP[14]}]
set_property PACKAGE_PIN C27 [get_ports {ID_DOWN_VALID[14]}]
set_property PACKAGE_PIN M24 [get_ports {ID_UP_VALID[14]}]
set_property PACKAGE_PIN A25 [get_ports {CMD_0[12]}]
set_property PACKAGE_PIN E28 [get_ports {CMD_1[12]}]
set_property PACKAGE_PIN B26 [get_ports {CMD_VALID[12]}]

#####slot14 : awg
set_property PACKAGE_PIN AE13 [get_ports {TRIGGER0_P[11]}]
set_property PACKAGE_PIN J30 [get_ports {DCO0_P[11]}]

set_property PACKAGE_PIN D30 [get_ports {ID_DOWN[15]}]
set_property PACKAGE_PIN J29 [get_ports {ID_UP[15]}]
set_property PACKAGE_PIN C29 [get_ports {ID_DOWN_VALID[15]}]
set_property PACKAGE_PIN L28 [get_ports {ID_UP_VALID[15]}]
set_property PACKAGE_PIN A29 [get_ports {CMD_0[13]}]
set_property PACKAGE_PIN D29 [get_ports {CMD_1[13]}]
set_property PACKAGE_PIN B29 [get_ports {CMD_VALID[13]}]

### FA_DCO0_P    FA_ID0_DOWN_  FA_ID0_UP_  FA_ID0_DOWN_VLD_
### FA_ID0_UP_VLD_   FA_GP0_CMD0_  FA_GP0_CMD1_   FA_CMD0_VLD_

set_property IOSTANDARD LVDS [get_ports {TRIGGER1_P[0]}]
set_property IOSTANDARD LVDS [get_ports {TRIGGER1_P[1]}]
set_property IOSTANDARD LVDS [get_ports {TRIGGER1_P[2]}]
set_property IOSTANDARD LVDS [get_ports {TRIGGER1_P[3]}]


set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[0]}]



set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[10]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[9]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[8]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[7]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[6]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[5]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[4]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[3]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[2]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER0_P[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER1_P[3]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER1_P[2]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER1_P[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {TRIGGER1_P[0]}]

set_false_path -from [get_pins trig_control_reg/C] -to [get_pins {obufds_trig1[*].trigger1_delay/delay_en_reg/D}]
set_false_path -from [get_pins trig_control_reg/C] -to [get_pins {obufds_trig0[*].trigger0_delay/delay_en_reg/D}]

#########debug

connect_debug_port dbg_hub/clk [get_nets clk_100M]

set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_DOWN_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_DOWN_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_DOWN_1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_DOWN_1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_DOWN_VALID[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_DOWN_VALID[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_UP_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_UP_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_UP_1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_UP_1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_UP_VALID[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_UP_VALID[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[0]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[10]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[9]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[8]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[7]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[6]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[5]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[4]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {DCO0_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DCO0_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DCO0_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {DCO0_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {DCO0_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {DCO0_N[0]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_P[3]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_N[3]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_P[2]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_N[2]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_P[1]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_N[1]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_P[0]}]
set_property IOSTANDARD LVDS [get_ports {DCO1_N[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[10]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[9]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[8]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[7]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[6]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[5]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[4]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[3]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[2]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO1_P[3]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO1_P[2]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO1_P[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO1_P[0]}]

set_property IOSTANDARD LVDS [get_ports {DCO0_P[11]}]
set_property IOSTANDARD LVDS [get_ports {DCO0_N[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_1[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CMD_VALID[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_DOWN_VALID[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ID_UP_VALID[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_P[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {TRIGGER0_N[11]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {DCO0_P[11]}]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100m]
